//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanielWillett.UnturnedDataFileLspServer.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiagnosticResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanielWillett.UnturnedDataFileLspServer.Data.Properties.DiagnosticResources", typeof(DiagnosticResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary and list properties can not also supply a value..
        /// </summary>
        internal static string UNT1001 {
            get {
                return ResourceManager.GetString("UNT1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected double quotation mark at end of quoted string..
        /// </summary>
        internal static string UNT1002 {
            get {
                return ResourceManager.GetString("UNT1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is a flag (no value) and supplying a value may be misleading or cause unexpected results..
        /// </summary>
        internal static string UNT1003 {
            get {
                return ResourceManager.GetString("UNT1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape sequence &apos;\{0}&apos; not recognized. Expected &apos;\n&apos;, &apos;\t&apos;, &apos;\&quot;&apos;, or &apos;\\&apos;..
        /// </summary>
        internal static string UNT1004 {
            get {
                return ResourceManager.GetString("UNT1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected for property &apos;{0}&apos;..
        /// </summary>
        internal static string UNT1005 {
            get {
                return ResourceManager.GetString("UNT1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property does not support rich text..
        /// </summary>
        internal static string UNT1006 {
            get {
                return ResourceManager.GetString("UNT1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; requires property &apos;{1}&apos; to be present..
        /// </summary>
        internal static string UNT1007 {
            get {
                return ResourceManager.GetString("UNT1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a face with this index, valid indexes include 0 through {0}..
        /// </summary>
        internal static string UNT1008_Beard {
            get {
                return ResourceManager.GetString("UNT1008_Beard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a beard with this index, valid indexes include 0 through {0}..
        /// </summary>
        internal static string UNT1008_Face {
            get {
                return ResourceManager.GetString("UNT1008_Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a hair with this index, valid indexes include 0 through {0}..
        /// </summary>
        internal static string UNT1008_Hair {
            get {
                return ResourceManager.GetString("UNT1008_Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown asset bundle version, expected a value between {0} and {1}..
        /// </summary>
        internal static string UNT1009 {
            get {
                return ResourceManager.GetString("UNT1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint supply IDs that are the same as their containing asset can be replaced with &apos;This&apos;..
        /// </summary>
        internal static string UNT101 {
            get {
                return ResourceManager.GetString("UNT101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths should only use forward slashes to maintain compatibility with Unity and Unix-based operating systems..
        /// </summary>
        internal static string UNT1010 {
            get {
                return ResourceManager.GetString("UNT1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path should match pattern &quot;{0}&quot;..
        /// </summary>
        internal static string UNT1011 {
            get {
                return ResourceManager.GetString("UNT1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This legacy color is expected to have components between 0 and 1. Using values outside this range may cause unexpected results or visual glitches..
        /// </summary>
        internal static string UNT1012 {
            get {
                return ResourceManager.GetString("UNT1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement ID &quot;{0}&quot; either doesn&apos;t exist or isn&apos;t a valid NPC achievement..
        /// </summary>
        internal static string UNT1013 {
            get {
                return ResourceManager.GetString("UNT1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value &quot;{0}&quot; isn&apos;t recognized. See documentation for a list of valid values..
        /// </summary>
        internal static string UNT1014 {
            get {
                return ResourceManager.GetString("UNT1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value &quot;{0}&quot; of enum &quot;{1}&quot; isn&apos;t recognized. See documentation for a list of valid values..
        /// </summary>
        internal static string UNT1014_Specific {
            get {
                return ResourceManager.GetString("UNT1014_Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a type deriving from &apos;{0}&apos;..
        /// </summary>
        internal static string UNT1015 {
            get {
                return ResourceManager.GetString("UNT1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0} is not a valid level for the {1} skill..
        /// </summary>
        internal static string UNT1016 {
            get {
                return ResourceManager.GetString("UNT1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected amount supplied for an item ID or GUID..
        /// </summary>
        internal static string UNT1017 {
            get {
                return ResourceManager.GetString("UNT1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; is deprecated..
        /// </summary>
        internal static string UNT1018 {
            get {
                return ResourceManager.GetString("UNT1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property shouldn&apos;t reference the asset it&apos;s defined in..
        /// </summary>
        internal static string UNT1019 {
            get {
                return ResourceManager.GetString("UNT1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This format string should include argument {{{0}}}..
        /// </summary>
        internal static string UNT102 {
            get {
                return ResourceManager.GetString("UNT102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;}&apos; at end of dictionary..
        /// </summary>
        internal static string UNT2001 {
            get {
                return ResourceManager.GetString("UNT2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;]&apos; at end of list..
        /// </summary>
        internal static string UNT2002 {
            get {
                return ResourceManager.GetString("UNT2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is a flag, meaning just the presence of the property equates to a &apos;true&apos; value. The &apos;{0}&apos; value here is ignored..
        /// </summary>
        internal static string UNT2003 {
            get {
                return ResourceManager.GetString("UNT2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; can not be converted to a value of type &apos;{1}&apos;..
        /// </summary>
        internal static string UNT2004 {
            get {
                return ResourceManager.GetString("UNT2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; can not be resolved..
        /// </summary>
        internal static string UNT2005 {
            get {
                return ResourceManager.GetString("UNT2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown asset bundle version, expected a value between {0} and {1}..
        /// </summary>
        internal static string UNT2009 {
            get {
                return ResourceManager.GetString("UNT2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A GUID is required for this asset..
        /// </summary>
        internal static string UNT2010 {
            get {
                return ResourceManager.GetString("UNT2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A legacy ID is required for this asset..
        /// </summary>
        internal static string UNT2011 {
            get {
                return ResourceManager.GetString("UNT2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed format string. Read about format strings here: https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-string-format#get-started-with-the-stringformat-method..
        /// </summary>
        internal static string UNT2012 {
            get {
                return ResourceManager.GetString("UNT2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed format string: {0}. Read about format strings here: https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-string-format#get-started-with-the-stringformat-method..
        /// </summary>
        internal static string UNT2012_WithMessage {
            get {
                return ResourceManager.GetString("UNT2012_WithMessage", resourceCulture);
            }
        }
    }
}
