//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanielWillett.UnturnedDataFileLspServer.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DiagnosticResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanielWillett.UnturnedDataFileLspServer.Data.Properties.DiagnosticResources", typeof(DiagnosticResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary and list properties can not also supply a value..
        /// </summary>
        public static string UNT1001 {
            get {
                return ResourceManager.GetString("UNT1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected double quotation mark at end of quoted string..
        /// </summary>
        public static string UNT1002 {
            get {
                return ResourceManager.GetString("UNT1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is a flag (no value) and supplying a value may be misleading or cause unexpected results..
        /// </summary>
        public static string UNT1003 {
            get {
                return ResourceManager.GetString("UNT1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape sequence &apos;\{0}&apos; not recognized. Expected &apos;\n&apos;, &apos;\t&apos;, &apos;\&quot;&apos;, or &apos;\\&apos;..
        /// </summary>
        public static string UNT1004 {
            get {
                return ResourceManager.GetString("UNT1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-quotation marks can not be escaped in non-quoted strings. Use quoted strings if the first character needs to be a double-quotation mark. For example: &quot;\&quot;Value\&quot;&quot;, which parses to [&quot;Value&quot;]..
        /// </summary>
        public static string UNT1004_LeadingEscapedSlash {
            get {
                return ResourceManager.GetString("UNT1004_LeadingEscapedSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing unescaped backslash. Use two backslashes to escape a backslash: &apos;\\&apos;..
        /// </summary>
        public static string UNT1004_Trailing {
            get {
                return ResourceManager.GetString("UNT1004_Trailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected for property &apos;{0}&apos;..
        /// </summary>
        public static string UNT1005 {
            get {
                return ResourceManager.GetString("UNT1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property does not support rich text..
        /// </summary>
        public static string UNT1006 {
            get {
                return ResourceManager.GetString("UNT1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; requires property &apos;{1}&apos; to be present..
        /// </summary>
        public static string UNT1007 {
            get {
                return ResourceManager.GetString("UNT1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a face with this index, valid indexes include 0 through {0}..
        /// </summary>
        public static string UNT1008_Beard {
            get {
                return ResourceManager.GetString("UNT1008_Beard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a beard with this index, valid indexes include 0 through {0}..
        /// </summary>
        public static string UNT1008_Face {
            get {
                return ResourceManager.GetString("UNT1008_Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a hair with this index, valid indexes include 0 through {0}..
        /// </summary>
        public static string UNT1008_Hair {
            get {
                return ResourceManager.GetString("UNT1008_Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown asset bundle version, expected a value between {0} and {1}..
        /// </summary>
        public static string UNT1009 {
            get {
                return ResourceManager.GetString("UNT1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint supply IDs that are the same as their containing asset can be replaced with &apos;This&apos;..
        /// </summary>
        public static string UNT101 {
            get {
                return ResourceManager.GetString("UNT101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;this&quot; keyword can be used to reference the current asset instead of using an ID or GUID..
        /// </summary>
        public static string UNT101_CodeFix_Annotation_Desc {
            get {
                return ResourceManager.GetString("UNT101_CodeFix_Annotation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &quot;this&quot; Keyword.
        /// </summary>
        public static string UNT101_CodeFix_Annotation_Label {
            get {
                return ResourceManager.GetString("UNT101_CodeFix_Annotation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths should only use forward slashes to maintain compatibility with Unity and Unix-based operating systems..
        /// </summary>
        public static string UNT1010 {
            get {
                return ResourceManager.GetString("UNT1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path should match pattern &quot;{0}&quot;..
        /// </summary>
        public static string UNT1011 {
            get {
                return ResourceManager.GetString("UNT1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This legacy color is expected to have components between 0 and 1. Using values outside this range may cause unexpected results or visual glitches..
        /// </summary>
        public static string UNT1012 {
            get {
                return ResourceManager.GetString("UNT1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement ID &quot;{0}&quot; either doesn&apos;t exist or isn&apos;t a valid NPC achievement..
        /// </summary>
        public static string UNT1013 {
            get {
                return ResourceManager.GetString("UNT1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value &quot;{0}&quot; isn&apos;t recognized. See documentation for a list of valid values..
        /// </summary>
        public static string UNT1014 {
            get {
                return ResourceManager.GetString("UNT1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one value in &quot;{0}&quot; of enum &quot;{1}&quot; isn&apos;t recognized. See documentation for a list of valid values..
        /// </summary>
        public static string UNT1014_Flags {
            get {
                return ResourceManager.GetString("UNT1014_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value &quot;{0}&quot; of enum &quot;{1}&quot; isn&apos;t recognized. See documentation for a list of valid values..
        /// </summary>
        public static string UNT1014_Specific {
            get {
                return ResourceManager.GetString("UNT1014_Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a type deriving from &apos;{0}&apos;..
        /// </summary>
        public static string UNT1015 {
            get {
                return ResourceManager.GetString("UNT1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0} is not a valid level for the {1} skill..
        /// </summary>
        public static string UNT1016 {
            get {
                return ResourceManager.GetString("UNT1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected amount supplied for an item ID or GUID..
        /// </summary>
        public static string UNT1017 {
            get {
                return ResourceManager.GetString("UNT1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; is deprecated..
        /// </summary>
        public static string UNT1018 {
            get {
                return ResourceManager.GetString("UNT1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Translation Reference format is no longer supported by Unturned..
        /// </summary>
        public static string UNT1018_TranslationReference {
            get {
                return ResourceManager.GetString("UNT1018_TranslationReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property shouldn&apos;t reference the asset it&apos;s defined in..
        /// </summary>
        public static string UNT1019 {
            get {
                return ResourceManager.GetString("UNT1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This format string should include argument {{{0}}}..
        /// </summary>
        public static string UNT102 {
            get {
                return ResourceManager.GetString("UNT102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document exceeds the maximum depth of the parser, which is {0} levels..
        /// </summary>
        public static string UNT1020 {
            get {
                return ResourceManager.GetString("UNT1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-line formatting is not supported for this string..
        /// </summary>
        public static string UNT1021 {
            get {
                return ResourceManager.GetString("UNT1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The correct new-line tag is &quot;&lt;br&gt;&quot;. No other variations are accepted..
        /// </summary>
        public static string UNT1022 {
            get {
                return ResourceManager.GetString("UNT1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type references should use assembly-qualified type names. These are formatted as the full type and the assembly name separated by a comma. For example: &apos;SDG.Unturned.Asset, Assembly-CSharp&apos;..
        /// </summary>
        public static string UNT1023 {
            get {
                return ResourceManager.GetString("UNT1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; should must contain at least {1} element(s)..
        /// </summary>
        public static string UNT1024_Less {
            get {
                return ResourceManager.GetString("UNT1024_Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; should not contain more than {1} element(s)..
        /// </summary>
        public static string UNT1024_More {
            get {
                return ResourceManager.GetString("UNT1024_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized property &quot;{0}&quot;. If you believe this is an error please open an issue on the GitHub page for this extension..
        /// </summary>
        public static string UNT1025 {
            get {
                return ResourceManager.GetString("UNT1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this property from the asset file since it&apos;s not recognized by Unturned..
        /// </summary>
        public static string UNT1025_CodeFix_Annotation_Desc {
            get {
                return ResourceManager.GetString("UNT1025_CodeFix_Annotation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &quot;{0}&quot; Property.
        /// </summary>
        public static string UNT1025_CodeFix_Annotation_Label {
            get {
                return ResourceManager.GetString("UNT1025_CodeFix_Annotation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is unknown and may not be assignable to &apos;{1}&apos;..
        /// </summary>
        public static string UNT103 {
            get {
                return ResourceManager.GetString("UNT103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MasterBundleReference (&quot;MasterBundle&quot;, &quot;AssetPath&quot;) format is preferred here over the legacy ContentReference (&quot;Name&quot;, &quot;Path&quot;) format..
        /// </summary>
        public static string UNT104 {
            get {
                return ResourceManager.GetString("UNT104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnecessary trailing comma after quoted string..
        /// </summary>
        public static string UNT105 {
            get {
                return ResourceManager.GetString("UNT105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &quot;&lt;br&gt;&quot; instead of an explicit new-line..
        /// </summary>
        public static string UNT106 {
            get {
                return ResourceManager.GetString("UNT106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a new GUID in the same format as the current one..
        /// </summary>
        public static string UNT107_CodeFix_Annotation_Desc {
            get {
                return ResourceManager.GetString("UNT107_CodeFix_Annotation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Random GUID.
        /// </summary>
        public static string UNT107_CodeFix_Annotation_Label {
            get {
                return ResourceManager.GetString("UNT107_CodeFix_Annotation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;}&apos; at end of dictionary..
        /// </summary>
        public static string UNT2001 {
            get {
                return ResourceManager.GetString("UNT2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;]&apos; at end of list..
        /// </summary>
        public static string UNT2002 {
            get {
                return ResourceManager.GetString("UNT2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is a flag, meaning just the presence of the property equates to a &apos;true&apos; value. The &apos;{0}&apos; value here is ignored..
        /// </summary>
        public static string UNT2003 {
            get {
                return ResourceManager.GetString("UNT2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; can not be converted to a value of type &apos;{1}&apos;..
        /// </summary>
        public static string UNT2004 {
            get {
                return ResourceManager.GetString("UNT2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; can not be resolved..
        /// </summary>
        public static string UNT2005 {
            get {
                return ResourceManager.GetString("UNT2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown asset bundle version, expected a value between {0} and {1}..
        /// </summary>
        public static string UNT2009 {
            get {
                return ResourceManager.GetString("UNT2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A GUID is required for this asset..
        /// </summary>
        public static string UNT2010 {
            get {
                return ResourceManager.GetString("UNT2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A legacy ID is required for this asset..
        /// </summary>
        public static string UNT2011 {
            get {
                return ResourceManager.GetString("UNT2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed format string. Read about format strings here: https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-string-format#get-started-with-the-stringformat-method..
        /// </summary>
        public static string UNT2012 {
            get {
                return ResourceManager.GetString("UNT2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed format string: {0}. Read about format strings here: https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-string-format#get-started-with-the-stringformat-method..
        /// </summary>
        public static string UNT2012_WithMessage {
            get {
                return ResourceManager.GetString("UNT2012_WithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} object can not be parsed using the legacy object format..
        /// </summary>
        public static string UNT2013_Legacy {
            get {
                return ResourceManager.GetString("UNT2013_Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} object can not be parsed using the modern object format..
        /// </summary>
        public static string UNT2013_Modern {
            get {
                return ResourceManager.GetString("UNT2013_Modern", resourceCulture);
            }
        }
    }
}
