//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanielWillett.UnturnedDataFileLspServer.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiagnosticResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiagnosticResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanielWillett.UnturnedDataFileLspServer.Data.Properties.DiagnosticResources", typeof(DiagnosticResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary and list properties can not also supply a value..
        /// </summary>
        internal static string UNT1001 {
            get {
                return ResourceManager.GetString("UNT1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected double quotation mark at end of quoted string..
        /// </summary>
        internal static string UNT1002 {
            get {
                return ResourceManager.GetString("UNT1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is a flag (no value) and supplying a value may be misleading or cause unexpected results..
        /// </summary>
        internal static string UNT1003 {
            get {
                return ResourceManager.GetString("UNT1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape sequence &apos;\{0}&apos; not recognized. Expected &apos;\n&apos;, &apos;\t&apos;, &apos;\&quot;&apos;, or &apos;\\&apos;..
        /// </summary>
        internal static string UNT1004 {
            get {
                return ResourceManager.GetString("UNT1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected for property &apos;{0}&apos;..
        /// </summary>
        internal static string UNT1005 {
            get {
                return ResourceManager.GetString("UNT1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property does not support rich text..
        /// </summary>
        internal static string UNT1006 {
            get {
                return ResourceManager.GetString("UNT1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; requires property &apos;{1}&apos; to be present..
        /// </summary>
        internal static string UNT1007 {
            get {
                return ResourceManager.GetString("UNT1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a face with this index, valid indexes include 0 through {0}..
        /// </summary>
        internal static string UNT1008_Beard {
            get {
                return ResourceManager.GetString("UNT1008_Beard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a beard with this index, valid indexes include 0 through {0}..
        /// </summary>
        internal static string UNT1008_Face {
            get {
                return ResourceManager.GetString("UNT1008_Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not a hair with this index, valid indexes include 0 through {0}..
        /// </summary>
        internal static string UNT1008_Hair {
            get {
                return ResourceManager.GetString("UNT1008_Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;}&apos; at end of dictionary..
        /// </summary>
        internal static string UNT2001 {
            get {
                return ResourceManager.GetString("UNT2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;]&apos; at end of list..
        /// </summary>
        internal static string UNT2002 {
            get {
                return ResourceManager.GetString("UNT2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is a flag, meaning just the presence of the property equates to a &apos;true&apos; value. The &apos;{0}&apos; value here is ignored..
        /// </summary>
        internal static string UNT2003 {
            get {
                return ResourceManager.GetString("UNT2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; can not be converted to a value of type &apos;{1}&apos;..
        /// </summary>
        internal static string UNT2004 {
            get {
                return ResourceManager.GetString("UNT2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; can not be resolved..
        /// </summary>
        internal static string UNT2005 {
            get {
                return ResourceManager.GetString("UNT2005", resourceCulture);
            }
        }
    }
}
