//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanielWillett.UnturnedDataFileLspServer.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanielWillett.UnturnedDataFileLspServer.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse IPv4Filter, expected a value in the format: &quot;0.0.0.0[/0][:0[-0]]&quot;..
        /// </summary>
        internal static string FormatException_IPv4Format_FailedToParse {
            get {
                return ResourceManager.GetString("FormatException_IPv4Format_FailedToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid count type: &apos;{0}&apos;. Expected an integer type..
        /// </summary>
        internal static string InvalidOperationException_InvalidCountType {
            get {
                return ResourceManager.GetString("InvalidOperationException_InvalidCountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download internet resource at &quot;{0}&quot;..
        /// </summary>
        internal static string Log_FailedToDownloadInternetResource {
            get {
                return ResourceManager.GetString("Log_FailedToDownloadInternetResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate embedded resource &quot;{0}&quot;, which was expected to exist..
        /// </summary>
        internal static string Log_FailedToFindEmbeddedResource {
            get {
                return ResourceManager.GetString("Log_FailedToFindEmbeddedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read resource at &quot;{0}&quot;..
        /// </summary>
        internal static string Log_FailedToParseResource {
            get {
                return ResourceManager.GetString("Log_FailedToParseResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string Type_Name_Boolean {
            get {
                return ResourceManager.GetString("Type_Name_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean or Flag.
        /// </summary>
        internal static string Type_Name_BooleanOrFlag {
            get {
                return ResourceManager.GetString("Type_Name_BooleanOrFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        internal static string Type_Name_Flag {
            get {
                return ResourceManager.GetString("Type_Name_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string Type_Name_Float128 {
            get {
                return ResourceManager.GetString("Type_Name_Float128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single-Precision Decimal.
        /// </summary>
        internal static string Type_Name_Float32 {
            get {
                return ResourceManager.GetString("Type_Name_Float32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-Precision Decimal.
        /// </summary>
        internal static string Type_Name_Float64 {
            get {
                return ResourceManager.GetString("Type_Name_Float64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed 16-Bit Integer.
        /// </summary>
        internal static string Type_Name_Int16 {
            get {
                return ResourceManager.GetString("Type_Name_Int16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed 32-Bit Integer.
        /// </summary>
        internal static string Type_Name_Int32 {
            get {
                return ResourceManager.GetString("Type_Name_Int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed 64-Bit Integer.
        /// </summary>
        internal static string Type_Name_Int64 {
            get {
                return ResourceManager.GetString("Type_Name_Int64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed 8-Bit Integer.
        /// </summary>
        internal static string Type_Name_Int8 {
            get {
                return ResourceManager.GetString("Type_Name_Int8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of {0}.
        /// </summary>
        internal static string Type_Name_List_Generic {
            get {
                return ResourceManager.GetString("Type_Name_List_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Type_Name_String {
            get {
                return ResourceManager.GetString("Type_Name_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned 16-Bit Integer.
        /// </summary>
        internal static string Type_Name_UInt16 {
            get {
                return ResourceManager.GetString("Type_Name_UInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned 32-Bit Integer.
        /// </summary>
        internal static string Type_Name_UInt32 {
            get {
                return ResourceManager.GetString("Type_Name_UInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned 64-Bit Integer.
        /// </summary>
        internal static string Type_Name_UInt64 {
            get {
                return ResourceManager.GetString("Type_Name_UInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned 8-Bit Integer.
        /// </summary>
        internal static string Type_Name_UInt8 {
            get {
                return ResourceManager.GetString("Type_Name_UInt8", resourceCulture);
            }
        }
    }
}
